const Depths = {

    BG_SCENE: 1,
    BG_ANIMATION: 2,

    ENEMIES: 25,
    ENEMIES_FROZEN: 19,
    ENEMIES_SPAWNED: 9,
    ENEMIES_CARRIED: 16,

    PLAYER_TEAM: 15,
    PLAYERS: 20,
    PLAYER_BULLETS: 21,

    BUILDINGS_BEHIND: 10,
    BUILDINGS_BG: 15,
    BUILDINGS_FG: 30,
    DECOR_FG: 45,

    FOREST_BG1: 10,
    FOREST_BG2: 11,
    FOREST_BG3: 12,
    FOREST_FG1: 35,
    FOREST_FG2: 40
}
export default Depths;