const Depths = {

    BG_SCENE: 1,
    BG_STAGE: 10,
    BG_GROUND_DEPTH: 9,
    BG_GROUND: 90,
    BG_ANIMATION: 3,
    BG_RUNNERS: 5,

    ENEMIES: 35,
    ENEMIES_FROZEN: 29,
    ENEMIES_SPAWNED: 19,
    ENEMIES_CARRIED: 26,
    ENEMIES_STOLEN: 34,
    ENEMIES_MOUND: 36,

    PLAYER_TEAM: 27,
    PLAYERS: 30,
    PLAYER_BULLETS: 31,

    CIVILIANS: 26,
    BUILDINGS_BEHIND: 15,
    BUILDINGS_BG: 25,
    BUILDINGS_FG: 40,
    DECOR_FG: 55,
    SCAFFOLD: 26,

    FOREST_BG1: 20,
    FOREST_BG2: 21,
    FOREST_BG3: 22,
    FOREST_FG1: 45,
    FOREST_FG2: 50,

    FREEZE_FX: 36,
    WIND_FX: 90,
}
export default Depths;