const Depths = {

    BG_SCENE: 1,
    BG_STAGE: 10,
    BG_ANIMATION: 3,

    ENEMIES: 35,
    ENEMIES_FROZEN: 29,
    ENEMIES_SPAWNED: 19,
    ENEMIES_CARRIED: 26,

    PLAYER_TEAM: 25,
    PLAYERS: 30,
    PLAYER_BULLETS: 31,

    BUILDINGS_BEHIND: 20,
    BUILDINGS_BG: 25,
    BUILDINGS_FG: 40,
    DECOR_FG: 55,

    FOREST_BG1: 20,
    FOREST_BG2: 21,
    FOREST_BG3: 22,
    FOREST_FG1: 45,
    FOREST_FG2: 50
}
export default Depths;